- name: test playbook
  hosts: localhost
  vars: 
    a: ["1", "2", "3"]
    b: ["a", "b", "c"]

  tasks:
    - debug:
        msg: "{{ item[0] }} - {{ item[1] }}"
      with_nested:
        - "{{ a }}"
        - "{{ b }}"
